version: '3'
services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: uofa/s2i-shepherd-drupal-dev
    # You will notice that we are forwarding port which do not belong to PHP.
    # We have to declare them here because these "sidecar" services are sharing
    # THIS containers network stack.
    ports:
      - "80:8080"
      - "3306:3306"
      - "8025:8025"
      - "9990:9990"
      - "11211:11211"
    environment:
      HASH_SALT: random-hash
      MEMCACHE_ENABLED: 0
      PHP_IDE_CONFIG: serverName=localhost
      PUBLIC_DIR: /shared/public
      REDIS_ENABLED: 1
      # REDIS_PASSWORD: testing
      SHEPHERD_INSTALL_PROFILE: ua
      SHEPHERD_SITE_ID: 2
      SHEPHERD_SECRET_PATH: /code/private
      SHEPHERD_TOKEN: super-secret-token
      SHEPHERD_URL: http://shepherd.test
      SITE_TITLE: WCMS D8
      SITE_MAIL: site@example.com
      SITE_ADMIN_EMAIL: admin@example.com
      SITE_ADMIN_USERNAME: admin
      SITE_ADMIN_PASSWORD: password
      XDEBUG_CONFIG: "remote_host=docker.for.mac.localhost"
    volumes:
      - nfsmount:/code
      - ./shared:/shared
      - $HOME/.ssh:/home/www-data/.ssh

  xdebug:
    image: nickschuch/d4m-tcp-forwarder
    network_mode: host
    environment:
      - PORT=9000

  db:
    image: mariadb
    network_mode: service:web
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: super-secret-password

  mail:
    image: mailhog/mailhog
    network_mode: service:web

  redis:
    image: redis:alpine
    command: |
      redis-server
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --save ""
    # --requirepass password
    network_mode: service:web

  memcached:
    image: jboss/infinispan-server:9.4.11.Final
    environment:
      APP_USER: user
      APP_PASS: pass
      MGMT_USER: admin
      MGMT_PASS: admin
    entrypoint:
      - docker-entrypoint.sh
      - -c
      - standalone-memcached.xml
    volumes:
      - ./docker/standalone-memcached.xml:/opt/jboss/infinispan-server/standalone/configuration/standalone-memcached.xml
    network_mode: service:web

  selenium:
    image: selenium/standalone-chrome:latest
    network_mode: service:web
    volumes:
      - /dev/shm:/dev/shm

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}"
